// <auto-generated />
namespace ClockStore.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_File_To_Catgory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_File_To_Catgory));
        
        string IMigrationMetadata.Id
        {
            get { return "201810122035164_Add_File_To_Catgory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
