// <auto-generated />
namespace ClockStore.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_TimeCounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_TimeCounter));
        
        string IMigrationMetadata.Id
        {
            get { return "201810221642568_Create_TimeCounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
