// <auto-generated />
namespace ClockStore.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_cantact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_cantact));
        
        string IMigrationMetadata.Id
        {
            get { return "201810071917239_Update_cantact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
