// <auto-generated />
namespace ClockStore.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_VideoHandler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_VideoHandler));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171905156_Create_VideoHandler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
