// <auto-generated />
namespace ClockStore.DTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_clock_desktop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_clock_desktop));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151727306_add_clock_desktop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
